---
language: java

jdk:
- openjdk7
matrix:
  include:
  - jdk: oraclejdk7
    script: mvn -q deploy --settings .travis-settings.xml -Dno.gem.deploy=true
  - jdk: oraclejdk8
    script: mvn -q deploy -P java8 -pl java8 --settings .travis-settings.xml -Dno.gem.deploy=true


branches:
  only:
  - master
notifications:
  email:
  - kglazko@mozilla.com
